### ISSUE TITLE
Why LLaMa pruning is difficult?

### ISSUE THREAD

**Issue by akisd2020** [IST-DASLab/sparsegpt#7]
Hi All, I have seen this repo which uses your algorithm to prune the Llama. Pruning LLama makes the accuracy very bad.  I am wondering if there is any explanation? have yo guys done pruning the LLaMa?

**Comment by songlinlibit** [comment]
Hi, could you share your pruning script? The llama model is similar with opt, so I think it should work

**Comment by Godofnothing** [comment]
Hi, @akisd2020 .LLaMA is more parameter efficient than OPT and bloom - hence It is natural that it is harder to maintain same performance using the same algorithm.

**Comment by Godofnothing** [comment]
@songlinlibit In the latest commit I've added LLaMA training script. Overall, all sparseGPT should be done for all CausalLM without significant changes

**Comment by efrantar** [comment]
In addition to what Denis said with LLaMa being more parameter efficient, the reconstruction process at the core of SparseGPT also appears to be less effective on LLaMa, either because there are less correlations between intermediate inputs that can be exploited and/or because the default calibration data that we used for OPT/BLOOM is not very well suited for LLaMa. In any case, improving SparseGPT specifically for pruning LLaMa is a great topic for further research. (Please also note that, in general, SparseGPT does work reasonably on LLaMa, but accuracy drops are generally a bit higher than for OPT/BLOOM; if you observe massive drops, then there might be some implementation problem.).
