### ISSUE TITLE
Gaussian elimination

### ISSUE THREAD

**Issue by Lihengwannafly** [IST-DASLab/sparsegpt#8]
I saw the "Hessian Synchronization" section in the paper, but it is not reflected in the code. Instead, it directly takes Hinv1 = Hinv[i1:i2, i1:i2]. What is the reason behind this?

**Comment by efrantar** [comment]
Hi, this is due to some extra optimizations which we omitted during our main discussion of the algorithm to convey the high level ideas as clearly as possible. First, the inverse Hessian sequence is computed in advance via a Cholesky decomposition, which essentially performs Gaussian elimination. Second, we lazily batch weight updates together to improve GPU utilization; this is why we subselect an inverse Hessian block, process the corresponding columns, and then batch update the remainder of the weight matrix in the end. You can read more about these optimizations in our related [GPTQ paper](https://arxiv.org/abs/2210.17323). Overall, these optimizations do not affect the algorithm (they are equivalent), but significantly improve speed and stability.
